# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: Next Meeting
run-name: ${{ github.actor }} has pushed content to GitHub

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup python (to install poetry)
        uses: actions/setup-python@v6

      - name: Install poetry
        run: pipx install --python `which python` poetry==2.2.1

      - name: Set up python (with caching)
        uses: actions/setup-python@v6
        with:
          cache: "poetry"

      - name: Install dependencies
        run: poetry install

      - name: Linting
        run: poetry run poe lint
      - name: Formatting
        run: poetry run poe format
      - name: Type checking
        run: poetry run poe types
      - name: Run test suite
        run: poetry run poe test -svvv --junitxml results.xml

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.21.0
        if: always()
        with:
          files: ./**/results.xml

    # This works, but produces a zip. Not entirely useful
    # - name: Archive code coverage results
    #   uses: actions/upload-artifact@v2
    #   if: always()
    #   with:
    #     name: code-coverage-report
    #     path: htmlcov/*

    # This requires a codecov.io account I think.
    # - name: Publish Code Coverage Report
    #   uses: codecov/codecov-action@v2
    #   if: always()
    #   with:
    #     files: ./coverage.xml
    #     verbose: true # optional (default = false)
