# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: Next Meeting
run-name: ${{ github.actor }} has pushed content to GitHub

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          cache: pipenv

      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
      - name: Install dependencies
        run: pipenv install --dev
    
      - name: Linting
        run: pipenv run lint
      - name: Formatting
        run: pipenv run black --check .
      - name: Type checking
        run: pipenv run types

      - name: Run test suite
        run: pipenv run test -svvv --junitxml results.xml

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.7.0
        if: always()
        with:
          files: ./**/results.xml

    # This works, but produces a zip. Not entirely useful
    # - name: Archive code coverage results
    #   uses: actions/upload-artifact@v2
    #   if: always()
    #   with:
    #     name: code-coverage-report
    #     path: htmlcov/*

    # This requires a codecov.io account I think.
    # - name: Publish Code Coverage Report
    #   uses: codecov/codecov-action@v2
    #   if: always()
    #   with:
    #     files: ./coverage.xml
    #     verbose: true # optional (default = false)
