# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: Next Meeting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

      # Setup Python (faster than using Python container)
    - name: Set up Python 3.9.2
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.2

    - name: Install pipenv
      run: |
        python -m pip install --upgrade pipenv wheel
    - id: cache-pipenv
      uses: actions/cache@v1
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

    - name: Install dependencies
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run: |
        pipenv install --deploy --dev
    
    - name: Linter
      run: |
        pipenv run lint

    - name: Type Checking
      run: |
        pipenv run types

    - name: Run test suite
      run: |
        pipenv run test -svvv --junitxml results.xml

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: ./**/results.xml

    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: htmlcov/*

    # - name: Publish Code Coverage Report
    #   uses: codecov/codecov-action@v2
    #   if: always()
    #   with:
    #     files: ./coverage.xml
    #     verbose: true # optional (default = false)
